# Azure Pipeline settings
# Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines

jobs:
- job: ubuntu_xenial_gcc_release
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    OS_NAME: linux
    COMPILER: gcc
    BUILD_TYPE: Release
    BUILD_DIR: $(Build.SourcesDirectory)
    LLVM_VERSION: 3.9
    PYTHON_VERSION: 3.5
    DOCKERFILE: Dockerfile.ubuntu-xenial
  steps:
  - template: .ci/azure-pipelines/docker.yml

- job: ubuntu_xenial_clang_release
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    OS_NAME: linux
    COMPILER: clang
    BUILD_TYPE: Release
    BUILD_DIR: $(Build.SourcesDirectory)
    LLVM_VERSION: 3.9
    PYTHON_VERSION: 3.5
    DOCKERFILE: Dockerfile.ubuntu-xenial
  steps:
  - template: .ci/azure-pipelines/docker.yml

- job: ubuntu_bionic_gcc_release
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    OS_NAME: linux
    COMPILER: gcc
    BUILD_TYPE: Release
    BUILD_DIR: $(Build.SourcesDirectory)
    LLVM_VERSION: 6.0
    PYTHON_VERSION: 3.6
    DOCKERFILE: Dockerfile.ubuntu-bionic
  steps:
  - template: .ci/azure-pipelines/docker.yml

- job: ubuntu_bionic_clang_release
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    OS_NAME: linux
    COMPILER: clang
    BUILD_TYPE: Release
    BUILD_DIR: $(Build.SourcesDirectory)
    LLVM_VERSION: 6.0
    PYTHON_VERSION: 3.6
    DOCKERFILE: Dockerfile.ubuntu-bionic
  steps:
  - template: .ci/azure-pipelines/docker.yml

- job: ubuntu_eoan_gcc_release
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    OS_NAME: linux
    COMPILER: gcc
    BUILD_TYPE: Release
    BUILD_DIR: $(Build.SourcesDirectory)
    LLVM_VERSION: 6.0  # 9 is the default but Chimera doesn't work with it
    PYTHON_VERSION: 3.7
    DOCKERFILE: Dockerfile.ubuntu-eoan
  steps:
  - template: .ci/azure-pipelines/docker.yml

- job: ubuntu_eoan_clang_release
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    OS_NAME: linux
    COMPILER: clang
    BUILD_TYPE: Release
    BUILD_DIR: $(Build.SourcesDirectory)
    LLVM_VERSION: 6.0  # 9 is the default but Chimera doesn't work with it
    PYTHON_VERSION: 3.7
    DOCKERFILE: Dockerfile.ubuntu-eoan
  steps:
  - template: .ci/azure-pipelines/docker.yml

- job: ubuntu_focal_gcc_release
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    OS_NAME: linux
    COMPILER: gcc
    BUILD_TYPE: Release
    BUILD_DIR: $(Build.SourcesDirectory)
    LLVM_VERSION: 6.0  # 10 is the default but Chimera doesn't work with it
    PYTHON_VERSION: 3.8
    DOCKERFILE: Dockerfile.ubuntu-focal
  steps:
  - template: .ci/azure-pipelines/docker.yml

- job: ubuntu_focal_clang_release
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    OS_NAME: linux
    COMPILER: clang
    BUILD_TYPE: Release
    BUILD_DIR: $(Build.SourcesDirectory)
    LLVM_VERSION: 6.0  # 10 is the default but Chimera doesn't work with it
    PYTHON_VERSION: 3.8
    DOCKERFILE: Dockerfile.ubuntu-focal
  steps:
  - template: .ci/azure-pipelines/docker.yml

- job: macos_mojave_clang_llvm6_release
  pool:
    vmImage: 'macOS 10.14'
  variables:
    OS_NAME: osx
    COMPILER: clang
    BUILD_TYPE: Release
    BUILD_DIR: $(Build.SourcesDirectory)
    LLVM_VERSION: 6
  steps:
  - script: |
      . .ci/install_macos.sh
      . .ci/script.sh
    displayName: 'Install/Script'
