language: cpp

sudo: required

dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug COVERALLS=ON COMPILER=GCC
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release COVERALLS=OFF COMPILER=GCC
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Debug COVERALLS=OFF COMPILER=CLANG
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release COVERALLS=OFF COMPILER=CLANG
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Debug COVERALLS=OFF COMPILER=CLANG
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Release COVERALLS=OFF COMPILER=CLANG

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 'ci/install_linux.sh'; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then 'ci/install_macos.sh'; fi

script:
  - mkdir build
  - cd build
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLLVM_DIR="/usr/share/llvm-3.6/cmake/" ..; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLLVM_DIR="/usr/local/Cellar/llvm/3.9.1/lib/cmake/llvm/" ..; fi
    # macOS tests are disabled because of the build errors due to a breaking 
    # change in the Clang API.
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make -j4; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make test; fi

after_failure: 
  - cat Testing/Temporary/LastTest.log
  - cat Testing/Temporary/LastTestsFailed.log
