FROM ubuntu:xenial

RUN apt-get update -qq
RUN apt-get install -y \
    build-essential  \
    cmake \
    curl \
    git \
    lib32z1-dev \
    lsb-release \
    pkg-config \
    python \
    software-properties-common \
    sudo \
    wget
