import unittest

import moduel_pybind11 as py11
import moduel_boost_python as boost


class TestModule(unittest.TestCase):

    def _test_typedef(self, binding):
        self.assertEqual(
            binding.__doc__, "The first example module generated by chimera")

    def test_typedef(self):
        self._test_typedef(boost)
        self._test_typedef(py11)


if __name__ == '__main__':
    unittest.main()
