import unittest

import module_pybind11 as py11
import module_boost_python as boost


class TestModule(unittest.TestCase):

    def _test_typedef(self, binding):
        if binding is py11:
            self.assertEqual(binding.__name__, "module_pybind11")
        elif binding is boost:
            self.assertEqual(binding.__name__, "module_boost_python")
        self.assertEqual(
            binding.__doc__, "The first example module generated by chimera")
        self.assertEqual(
            binding.__version__, "0.1.0")

    def test_typedef(self):
        self._test_typedef(boost)
        self._test_typedef(py11)


if __name__ == '__main__':
    unittest.main()
